### ISSUE TITLE
下载项目只会npm run dev 报错

### ISSUE THREAD

**Issue by wangyinwei1** [landluck/react-ant-admin-api#3]
![image](https://user-images.githubusercontent.com/15857725/76670911-25332a80-65ce-11ea-9bc7-1eda4b5968ed.png)
![image](https://user-images.githubusercontent.com/15857725/76670927-4c89f780-65ce-11ea-99cb-89f1bd5e6ec1.png)

**Comment by william-xue** [comment]
你数据库链接有问题 看看是不是数据库方面哪里

**Comment by landluck** [comment]
说的没错，你本地数据库连接不上
