### ISSUE TITLE
优化咨询

### ISSUE THREAD

**Issue by pengjugame** [landluck/react-ant-admin-api#5]
这个框架是目前见到的代码质量非常高的一个框架，从中学到了不少内容，在此过程中有问题想和您咨询一下：

- 路由加了`router.prefix('/react-ant-admin-api');` 在使用的过程中，如果使用了它，就逃不过auth的过滤，除非在config.auth加上此配置，不使用当然没问题，但我想您的设计思想本来也是需要带一个总体路由目录（我也这样想），我应该如何再去优化一下？

请您指导一下，谢谢。

**Comment by pengjugame** [comment]
还有一个问题继续请教一下。
如果我现在把用户分成 `注册用户` 和 `管理用户`， 注册用户有挺多的业务，管理用户主要是后台一些查询修改之类的，那么这个User我是否可以用同一个呢？还是应该把它直接分成两个没任何关系的用户好呢？
希望能得到您的指导。谢谢。

**Comment by landluck** [comment]
sql admin和uvs之类的都是一个值，你可以在 config 中添加一个配置，在 model 定义中去读就可以了，这样就可以统一了，至于 router.prefix('/react-ant-admin-api') 这个，可加可不加，具体看你nginx之类的怎么配置，config.auth 改一下，比如正则，或者是别的之类的，方法有很多，都可以实现



在 2020-04-07 01:24:04，"LiPengJu" <notifications@github.com> 写道：

这个框架是目前见到的代码质量非常高的一个框架，从中学到了不少内容，在此过程中有以下几个问题想和您咨询一下：

Sql前缀是admin，脚本Model的前缀是uvs，万一之后改个表名之类的，这些内容我应该如何优化一下（加个适配器什么的）？或者压根不用优化直接手动改即可（其实想想也没多少表）？

路由加了router.prefix('/react-ant-admin-api'); 在使用的过程中，如果使用了它，就逃不过auth的过滤，除非在config.auth加上此配置，不使用当然没问题，但我想您的设计思想本来也是需要带一个总体路由目录（我也这样想），我应该如何再去优化一下？

请您指导一下，谢谢。

**Comment by landluck** [comment]
看你的两种用户有没有本质区别，比如说A类是公司内部员工，B类是外部用户，那很有必要完全分开，如果都是同一种，分开的必要性不是很大，多一种用户就多了很多开发和维护成本，个人建议

**Comment by pengjugame** [comment]
明白了，就按这么说的加。
如此看来我确实需要分开前台用户和后台用户了，之前还挺犹豫，现在整体就比较清楚了，谢谢。
